// Loading 特效
export const SET_MAIN_LOADING = 'SET_MAIN_LOADING'
// 图片显示
export const SET_PICTURE_MODAL = 'SET_PICTURE_MODAL'
// 会员信息
export const SET_USER_INFO = 'SET_USER_INFO'

// 活动
export const SET_ACTIVITY_LIST = 'SET_ACTIVITY_LIST'
export const SET_ACTIVITY_DETAIL = 'SET_ACTIVITY_DETAIL'
export const CHANGE_ACTIVITY_LIST = 'CHANGE_ACTIVITY_LIST'
